SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC
SELECT NAME,DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION='Sick'
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION<>'Aged' ORDER BY ANIMAL_ID ASC
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME,DATETIME DESC
— 상위 n개 레코드 (LIMIT)
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1 

— 최댓값 구하기 (MAX)
SELECT MAX(DATETIME) AS 시간 FROM ANIMAL_INS
— 최솟값 구하기 (MIN)
SELECT MIN(DATETIME) AS 시간 FROM ANIMAL_INS

— 개수 구하기 (COUNT)
SELECT COUNT(*) AS count FROM ANIMAL_INS

—중복 제거하기 (DISTINCT)
SELECT COUNT(DISTINCT NAME) AS count FROM ANIMAL_INS

— 그룹화하기
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS count FROM ANIMAL_INS 
GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE

— 동명 동물 수 찾기
SELECT NAME,COUNT(NAME) AS 'COUNT' FROM ANIMAL_INS GROUP BY NAME HAVING COUNT(NAME)>1 ORDER BY NAME 
